const Memobird = require('memobird');
const canvas = document.getElementById('canvas-id'); // 获取canvas对象
const bmp = Memobird.encodeCanvas(canvas); // 将canvas转为单色点位图base64编码值
// ...
// 省略代码：将bmp的值传给服务器
// ...

// ...
// 省略代码：接收客户端发来的bmp的值
// ...
memobird.init()
  .then(() => memobird.print(bmp));
